# Generated by Django 2.2.12 on 2020-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未分配', help_text='项目名称', max_length=50, unique=True, verbose_name='项目名称')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未分配', help_text='项目大区', max_length=50, unique=True, verbose_name='项目大区')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目大区',
                'verbose_name_plural': '项目大区',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未分配', help_text='项目角色', max_length=50, unique=True, verbose_name='项目角色')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目角色',
                'verbose_name_plural': '项目角色',
                'ordering': ('id',),
            },
        ),
    ]
