# Generated by Django 2.2.12 on 2020-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='区域', help_text='项目角色', max_length=50, unique=True, verbose_name='区域')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'ordering': ('id',),
            },
        ),
    ]
