# Generated by Django 2.2.12 on 2020-06-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadbook',
            name='book',
        ),
    ]
