# Generated by Django 2.2.12 on 2020-06-05 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_uploadbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbook',
            name='book',
            field=models.FileField(default=django.utils.timezone.now, upload_to='books', verbose_name='文件上传'),
            preserve_default=False,
        ),
    ]
