# Generated by Django 3.0.4 on 2020-04-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, help_text='主机名', max_length=200, verbose_name='主机名')),
                ('public_ip', models.GenericIPAddressField(blank=True, help_text='外网IP', null=True, verbose_name='外网IP')),
                ('private_ip', models.GenericIPAddressField(help_text='内网IP', unique=True, verbose_name='内网IP')),
                ('os', models.CharField(blank=True, default=None, help_text='操作系统', max_length=100, verbose_name='操作系统')),
                ('cpu', models.CharField(blank=True, default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息')),
                ('memory', models.CharField(blank=True, default=None, help_text='内存信息', max_length=100, verbose_name='内存信息')),
                ('disk', models.CharField(blank=True, help_text='硬盘信息', max_length=300, null=True, verbose_name='硬盘信息')),
                ('status', models.BooleanField(default=False, help_text='是否启用', verbose_name='启用')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('area', models.ForeignKey(help_text='所属大区', on_delete=django.db.models.deletion.DO_NOTHING, related_name='server_area', to='project.ProjectArea')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.DO_NOTHING, related_name='server_project', to='project.Project')),
                ('role', models.ForeignKey(help_text='角色', on_delete=django.db.models.deletion.DO_NOTHING, related_name='server_role', to='project.ProjectRole')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
                'ordering': ('id',),
            },
        ),
    ]
