# Generated by Django 2.2.12 on 2020-06-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectregion'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.ForeignKey(blank=True, help_text='区域', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_region', to='project.ProjectRegion', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_project', to='project.Project', verbose_name='项目'),
        ),
    ]
