# Generated by Django 3.0.4 on 2020-04-13 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='area',
            field=models.ForeignKey(default=1, help_text='所属大区', on_delete=django.db.models.deletion.DO_NOTHING, related_name='server_area', to='project.ProjectArea'),
        ),
    ]
