# Generated by Django 3.0.4 on 2020-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20200413_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='area',
            field=models.CharField(choices=[('0', '未分配'), ('101', '测试大区'), ('102', '提审大区'), ('103', '预发布大区'), ('104', '正式大区')], default='0', help_text='大区', max_length=50, verbose_name='大区'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.CharField(choices=[('未分配', '未分配'), ('王者荣耀', '王者荣耀'), ('和平精英', '和平精英')], default='空闲', help_text='项目', max_length=50, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='server',
            name='role',
            field=models.CharField(choices=[('未分配', '未分配'), ('login', 'login'), ('idip', 'idip'), ('game', 'game'), ('match', 'match'), ('battlematch', 'battlematch'), ('battle', 'battle')], default='空闲', help_text='功能', max_length=50, verbose_name='功能'),
        ),
    ]
