# Generated by Django 2.2.12 on 2020-06-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200602_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='avatar',
        ),
    ]
