# Generated by Django 2.2.12 on 2020-06-11 11:22

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rbac', '0003_auto_20200603_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Permission')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
