# Generated by Django 2.2.12 on 2020-06-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20200613_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blacklist',
            new_name='IpWhiteList',
        ),
    ]
